
const APP_DEFAULT_COLOR_1 = '#fff';
const APP_DEFAULT_COLOR_2 = '#328c73';
const APP_DEFAULT_COLOR_3 = '#45bf9d';
const APP_DEFAULT_COLOR_4 = '#E3E3E3';
const APP_DEFAULT_COLOR_5 = '#F7F7F7';

const APP_STATUS_BAR_COLOR_1 = '#404040';
const APP_STATUS_BAR_COLOR_2 = '#fff';

const APP_TEXT_COLOR_WHITE = '#404040';

export {
  APP_DEFAULT_COLOR_1,
  APP_DEFAULT_COLOR_2,
  APP_DEFAULT_COLOR_3,
  APP_DEFAULT_COLOR_4,
  APP_DEFAULT_COLOR_5,
  APP_STATUS_BAR_COLOR_1,
  APP_STATUS_BAR_COLOR_2,
  APP_TEXT_COLOR_WHITE
}