
const APP_DEFAULT_COLOR_1 = '#006C7F';
const APP_DEFAULT_COLOR_2 = '#4CE4FF';
const APP_DEFAULT_COLOR_3 = '#00D8FF';
const APP_DEFAULT_COLOR_4 = '#106E7F';
const APP_DEFAULT_COLOR_5 = '#00ADCC';

const APP_STATUS_BAR_COLOR_1 = '#FFF';
const APP_STATUS_BAR_COLOR_2 = '#106E7F';

const APP_TEXT_COLOR_WHITE = '#fff';

export {
  APP_DEFAULT_COLOR_1,
  APP_DEFAULT_COLOR_2,
  APP_DEFAULT_COLOR_3,
  APP_DEFAULT_COLOR_4,
  APP_DEFAULT_COLOR_5,
  APP_STATUS_BAR_COLOR_1,
  APP_STATUS_BAR_COLOR_2,
  APP_TEXT_COLOR_WHITE
}