
const APP_DEFAULT_COLOR_1 = '#fff';
const APP_DEFAULT_COLOR_2 = '#4CE4FF';
const APP_DEFAULT_COLOR_3 = '#00D8FF';
const APP_DEFAULT_COLOR_4 = '#106E7F';
const APP_DEFAULT_COLOR_5 = '#00ADCC';

const APP_STATUS_BAR_COLOR_1 = '#404040';
const APP_STATUS_BAR_COLOR_2 = '#fff';

const APP_TEXT_COLOR_WHITE = '#404040';

const APP_REQUEST_LOGIN_SERVER = {
  'address': '127.0.0.1/server/mspirn/app/auth/'
}

const APP_VALIDATOR_ACCESS_TOKEN = '08ee4c0ad551ba3d969fecc510092db0';
const APP_VALIDATOR_CPF_TOKEN = 'http://geradorapp.com/api/v1/cpf/validate/{NUM}?08ee4c0ad551ba3d969fecc510092db0';
const APP_VALIDATOR_CNS_TOKEN = 'http://geradorapp.com/api/v1/cns/validate/{NUM}?08ee4c0ad551ba3d969fecc510092db0';

export {
  APP_DEFAULT_COLOR_1,
  APP_DEFAULT_COLOR_2,
  APP_DEFAULT_COLOR_3,
  APP_DEFAULT_COLOR_4,
  APP_DEFAULT_COLOR_5,
  APP_STATUS_BAR_COLOR_1,
  APP_STATUS_BAR_COLOR_2,
  APP_TEXT_COLOR_WHITE,
  APP_REQUEST_LOGIN_SERVER,
  APP_VALIDATOR_ACCESS_TOKEN,
  APP_VALIDATOR_CPF_TOKEN,
  APP_VALIDATOR_CNS_TOKEN
}